services:
  translator:
    build:
      context: '.'
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
